include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - dart_code_linter

dart_code_linter:
  rules:
    - avoid-unused-parameters

formatter:
  page_width: 120
