name: plezy
description: "Plezy GKUI compatibility fork"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.4 <3.4.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/plezy.png
  fonts:
    - family: PlezySans
      fonts:
        - asset: assets/droid-sans.ttf
